### ISSUE TITLE
Pure/impure graph generation

### ISSUE THREAD

**Issue by TheBeardedQuack** [kstrafe/Cxy#3]
Hey, it's been a while since we spoke.

I know this is definitely the wrong place, but I can't seem to find you on the platforms I have, so maybe I can grab your attention and then close the issue?

I remember you showing me the graphs generated for this language and how you had this idea of a "pure" function. I feel this would be a really great tool for aiding library/software development. Especially when updating an existing code-base to add features or retroactively add unit-testing. I was wondering if you might be able to go over some of this with me?

**Comment by kstrafe** [comment]
I think I've always just written a simple outputter that writes into graphviz/dot format. Hopefully that'll help you out. Are you on discord? Or were you from the Skype days? Unfortunately can't recall who you are. Let me know 🙂

**Comment by TheBeardedQuack** [comment]
So I can certainly learn how to interface with graphviz/dot, it's really the analysis of the classes/functions to classify them that I have no idea how to do. I guess if you were making the language a lot of this info could've come from the parser itself?

I was in the Skype group back in the day, we all moved over to Discord (https://discord.gg/mU5uR6u) to make it easier to handle, but then everyone went silent and there's not much engagement anymore which is a real shame.
